FROM python:3.12-rc-alpine3.17

WORKDIR ./Ai_software_stability/Ai_software_stability_backend_code/Ai_software_stability_backend_code/api.py

COPY . /api

#RUN pip install -r requirements.txt

COPY requirements.txt .


CMD ["python","api.py"]
